/*
Insert (MongoDB) de Indicador generado por codigo
Autores: Laura Sanchez y Felipe Ruiz. (Pareja 11 del grupo 6212)
Gestion de Datos Biomedicos. Practica 4
*/

db.Indicador.drop();
db.Indicador.createIndex({CodigoI:1}, {unique:true});
var Indicador=
[
	{'CodigoI':'HLTHRES_1', 'DescripcionI':'Associate nurses employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_2', 'DescripcionI':'Associate nurses employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_3', 'DescripcionI':'Associate professional midwives, licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_4', 'DescripcionI':'Associate professional midwives, licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_5', 'DescripcionI':'Associate professional midwives, practising, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_6', 'DescripcionI':'Associate professional midwives, practising, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_7', 'DescripcionI':'Associate professional midwives, professionally active, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_8', 'DescripcionI':'Associate professional midwives, professionally active, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_9', 'DescripcionI':'Associate professional nurses employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_10', 'DescripcionI':'Associate professional nurses employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_11', 'DescripcionI':'Associate professional nurses, licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_12', 'DescripcionI':'Associate professional nurses, licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_13', 'DescripcionI':'Associate professional nurses, practising, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_14', 'DescripcionI':'Associate professional nurses, practising, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_15', 'DescripcionI':'Associate professional nurses, professionally active, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_16', 'DescripcionI':'Associate professional nurses, professionally active, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_17', 'DescripcionI':'Associate professional nursing graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_18', 'DescripcionI':'Associate professional nursing graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_19', 'DescripcionI':'Beds in for–profit privately owned hospitals, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_20', 'DescripcionI':'Beds in for–profit privately owned hospitals, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_21', 'DescripcionI':'Beds in not–for–profit privately owned hospitals, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_22', 'DescripcionI':'Beds in not–for–profit privately owned hospitals, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_23', 'DescripcionI':'Beds in nursing and residential care facilities, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_24', 'DescripcionI':'Beds in nursing and residential care facilities, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_25', 'DescripcionI':'Beds in privately owned hospitals, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_26', 'DescripcionI':'Beds in privately owned hospitals, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_27', 'DescripcionI':'Beds in publicly owned hospitals, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_28', 'DescripcionI':'Beds in publicly owned hospitals, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_29', 'DescripcionI':'Caring personnel, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_30', 'DescripcionI':'Caring personnel, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_31', 'DescripcionI':'Computed Tomography Scanners in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_32', 'DescripcionI':'Computed Tomography Scanners in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_33', 'DescripcionI':'Computed Tomography Scanners in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_34', 'DescripcionI':'Computed Tomography Scanners in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_35', 'DescripcionI':'Computed Tomography Scanners, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_36', 'DescripcionI':'Computed Tomography Scanners, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_37', 'DescripcionI':'Computed Tomography Scanners, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_38', 'DescripcionI':'Computed Tomography Scanners, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_39', 'DescripcionI':'Curative (acute) care beds, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_40', 'DescripcionI':'Curative (acute) care beds, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_41', 'DescripcionI':'Dentists graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_42', 'DescripcionI':'Dentists graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_43', 'DescripcionI':'Dentists licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_44', 'DescripcionI':'Dentists licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_45', 'DescripcionI':'Dentists, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_46', 'DescripcionI':'Dentists, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_47', 'DescripcionI':'Digital subtraction angiography units in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_48', 'DescripcionI':'Digital subtraction angiography units in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_49', 'DescripcionI':'Digital subtraction angiography units in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_50', 'DescripcionI':'Digital subtraction angiography units in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_51', 'DescripcionI':'Digital subtraction angiography units , % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_52', 'DescripcionI':'Digital subtraction angiography units , % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_53', 'DescripcionI':'Digital subtraction angiography units , per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_54', 'DescripcionI':'Digital subtraction angiography units , total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_55', 'DescripcionI':'For–profit privately owned hospitals, per 100 000 population', 'Unidad':'FACIL_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_56', 'DescripcionI':'For–profit privately owned hospitals, total number', 'Unidad':'NUM_FACIL', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_57', 'DescripcionI':'Gamma cameras in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_58', 'DescripcionI':'Gamma cameras in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_59', 'DescripcionI':'Gamma cameras in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_60', 'DescripcionI':'Gamma cameras in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_61', 'DescripcionI':'Gamma cameras, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_62', 'DescripcionI':'Gamma cameras, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_63', 'DescripcionI':'Gamma cameras, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_64', 'DescripcionI':'Gamma cameras, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_65', 'DescripcionI':'General hospitals, per 100 000 population', 'Unidad':'FACIL_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_66', 'DescripcionI':'General hospitals, total number', 'Unidad':'NUM_FACIL', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_67', 'DescripcionI':'Generalist medical practitioners, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_68', 'DescripcionI':'Generalist medical practitioners, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_69', 'DescripcionI':'General paediatricians, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_70', 'DescripcionI':'General paediatricians, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_71', 'DescripcionI':'General practitioners, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_72', 'DescripcionI':'General practitioners, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_73', 'DescripcionI':'Health care assistants employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_74', 'DescripcionI':'Health care assistants employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_75', 'DescripcionI':'Health care assistants employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_76', 'DescripcionI':'Health care assistants employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_77', 'DescripcionI':'Hospitals, per 100 000 population', 'Unidad':'FACIL_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_78', 'DescripcionI':'Hospitals, total number', 'Unidad':'NUM_FACIL', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_79', 'DescripcionI':'Lithotripters in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_80', 'DescripcionI':'Lithotripters in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_81', 'DescripcionI':'Lithotripters in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_82', 'DescripcionI':'Lithotripters in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_83', 'DescripcionI':'Lithotripters, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_84', 'DescripcionI':'Lithotripters, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_85', 'DescripcionI':'Lithotripters, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_86', 'DescripcionI':'Lithotripters, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_87', 'DescripcionI':'Long–term care beds (excl. psychiatric beds), per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_88', 'DescripcionI':'Long–term care beds (excl. psychiatric beds), total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_89', 'DescripcionI':'Magnetic Resonance Imaging Units in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_90', 'DescripcionI':'Magnetic Resonance Imaging Units in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_91', 'DescripcionI':'Magnetic Resonance Imaging Units in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_92', 'DescripcionI':'Magnetic Resonance Imaging Units in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_93', 'DescripcionI':'Magnetic Resonance Imaging Units, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_94', 'DescripcionI':'Magnetic Resonance Imaging Units, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_95', 'DescripcionI':'Magnetic Resonance Imaging Units, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_96', 'DescripcionI':'Magnetic Resonance Imaging Units, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_97', 'DescripcionI':'Mammographs in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_98', 'DescripcionI':'Mammographs in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_99', 'DescripcionI':'Mammographs in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_100', 'DescripcionI':'Mammographs in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_101', 'DescripcionI':'Mammographs, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_102', 'DescripcionI':'Mammographs, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_103', 'DescripcionI':'Mammographs, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_104', 'DescripcionI':'Mammographs, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_105', 'DescripcionI':'Medical doctors not further defined, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_106', 'DescripcionI':'Medical doctors not further defined, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_107', 'DescripcionI':'Medical graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_108', 'DescripcionI':'Medical graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_109', 'DescripcionI':'Medical group of specialists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_110', 'DescripcionI':'Medical group of specialists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_111', 'DescripcionI':'Midwifes, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_112', 'DescripcionI':'Midwifes, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_113', 'DescripcionI':'Midwives graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_114', 'DescripcionI':'Midwives graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_115', 'DescripcionI':'Midwives licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_116', 'DescripcionI':'Midwives licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_117', 'DescripcionI':'Not–for–profit privately owned hospitals, per 100 000 population', 'Unidad':'FACIL_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_118', 'DescripcionI':'Not–for–profit privately owned hospitals, total number', 'Unidad':'NUM_FACIL', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_119', 'DescripcionI':'Nurses and midwives employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_120', 'DescripcionI':'Nurses and midwives employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_121', 'DescripcionI':'Nurses and midwives, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_122', 'DescripcionI':'Nurses and midwives, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_123', 'DescripcionI':'Nurses licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_124', 'DescripcionI':'Nurses licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_125', 'DescripcionI':'Nurses per 100 physicians in hospitals,', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_126', 'DescripcionI':'Nurses, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_127', 'DescripcionI':'Nurses, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_128', 'DescripcionI':'Nursing graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_129', 'DescripcionI':'Nursing graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_130', 'DescripcionI':'Obstetricians and gynaecologists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_131', 'DescripcionI':'Obstetricians and gynaecologists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_132', 'DescripcionI':'% of nurses and midwives working in hospitals', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_133', 'DescripcionI':'% of physicians, both sexes, 35–44 years old', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_134', 'DescripcionI':'% of physicians, both sexes, 45–54 years old', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_135', 'DescripcionI':'% of physicians, both sexes, 55–64 years old', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_136', 'DescripcionI':'% of physicians, both sexes, 65 years old or older', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_137', 'DescripcionI':'% of physicians by sex, all ages', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_138', 'DescripcionI':'% of physicians working in hospitals,', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_139', 'DescripcionI':'% of physicians, both sexes, younger than 35 years', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_140', 'DescripcionI':'Other generalist (non–specialist) medical practitioners, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_141', 'DescripcionI':'Other generalist (non–specialist) medical practitioners, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_142', 'DescripcionI':'Other health service providers employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_143', 'DescripcionI':'Other health service providers employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_144', 'DescripcionI':'Other health service providers employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_145', 'DescripcionI':'Other health service providers employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_146', 'DescripcionI':'Other hospital beds, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_147', 'DescripcionI':'Other hospital beds, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_148', 'DescripcionI':'Other specialists not elsewhere classified, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_149', 'DescripcionI':'Other specialists not elsewhere classified, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_150', 'DescripcionI':'Other staff employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_151', 'DescripcionI':'Other staff employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_152', 'DescripcionI':'Other staff employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_153', 'DescripcionI':'Other staff employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_154', 'DescripcionI':'Pharmacists graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_155', 'DescripcionI':'Pharmacists graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J00'},
	{'CodigoI':'HLTHRES_156', 'DescripcionI':'Pharmacists licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_157', 'DescripcionI':'Pharmacists licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_158', 'DescripcionI':'Pharmacists, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_159', 'DescripcionI':'Pharmacists, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_160', 'DescripcionI':'Physicians, both sexes, 35–44 years old', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_161', 'DescripcionI':'Physicians, both sexes, 45–54 years old', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_162', 'DescripcionI':'Physicians, both sexes, 55–64 years old', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_163', 'DescripcionI':'Physicians, both sexes, 65 years old or older', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_164', 'DescripcionI':'Physicians, both sexes, all ages', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_165', 'DescripcionI':'Physicians employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_166', 'DescripcionI':'Physicians employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_167', 'DescripcionI':'Physicians employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_168', 'DescripcionI':'Physicians employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_169', 'DescripcionI':'Physicians licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_170', 'DescripcionI':'Physicians licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_171', 'DescripcionI':'Physicians, practising or closest concept, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_172', 'DescripcionI':'Physicians, practising or closest concept, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_173', 'DescripcionI':'Physicians, both sexes, younger than 35 years', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_174', 'DescripcionI':'Population used as denominator, both sexes', 'Unidad':'NUM_PERS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_175', 'DescripcionI':'Positron Emission Tomography scanners in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_176', 'DescripcionI':'Positron Emission Tomography scanners in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_177', 'DescripcionI':'Positron Emission Tomography scanners in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_178', 'DescripcionI':'Positron Emission Tomography scanners in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_179', 'DescripcionI':'Positron Emission Tomography scanners , % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_180', 'DescripcionI':'Positron Emission Tomography scanners , % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_181', 'DescripcionI':'Positron Emission Tomography scanners , per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_182', 'DescripcionI':'Positron Emission Tomography scanners , total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_183', 'DescripcionI':'Practising caring personnel (personal care workers), per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_184', 'DescripcionI':'Practising caring personnel (personal care workers), total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_185', 'DescripcionI':'Practising dentists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_186', 'DescripcionI':'Practising dentists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_187', 'DescripcionI':'Practising midwives, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_188', 'DescripcionI':'Practising midwives, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_189', 'DescripcionI':'Practising nurses, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_190', 'DescripcionI':'Practising nurses, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_191', 'DescripcionI':'Practising pharmacists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_192', 'DescripcionI':'Practising pharmacists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_193', 'DescripcionI':'Practising physicians, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_194', 'DescripcionI':'Practising physicians, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_195', 'DescripcionI':'Practising physiotherapists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_196', 'DescripcionI':'Practising physiotherapists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_197', 'DescripcionI':'Professionally active caring personnel (personal care workers), per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_198', 'DescripcionI':'Professionally active caring personnel (personal care workers), total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_199', 'DescripcionI':'Professionally active dentists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_200', 'DescripcionI':'Professionally active dentists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_201', 'DescripcionI':'Professionally active midwives, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_202', 'DescripcionI':'Professionally active midwives, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_203', 'DescripcionI':'Professionally active nurses, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_204', 'DescripcionI':'Professionally active nurses, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_205', 'DescripcionI':'Professionally active pharmacists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_206', 'DescripcionI':'Professionally active pharmacists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_207', 'DescripcionI':'Professionally active physicians, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_208', 'DescripcionI':'Professionally active physicians, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_209', 'DescripcionI':'Professional midwives, licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_210', 'DescripcionI':'Professional midwives, licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_211', 'DescripcionI':'Professional midwives, practising, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_212', 'DescripcionI':'Professional midwives, practising, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_213', 'DescripcionI':'Professional midwives, professionally active, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_214', 'DescripcionI':'Professional midwives, professionally active, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_215', 'DescripcionI':'Professional nurses and midwives employed by hospital in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_216', 'DescripcionI':'Professional nurses and midwives employed by hospital in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_217', 'DescripcionI':'Professional nurses and midwives employed by hospital, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_218', 'DescripcionI':'Professional nurses and midwives employed by hospital, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_219', 'DescripcionI':'Professional nurses, licensed to practice, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_220', 'DescripcionI':'Professional nurses, licensed to practice, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_221', 'DescripcionI':'Professional nurses, practising, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_222', 'DescripcionI':'Professional nurses, practising, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_223', 'DescripcionI':'Professional nurses, professionally active, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_224', 'DescripcionI':'Professional nurses, professionally active, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_225', 'DescripcionI':'Professional nursing graduates, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_226', 'DescripcionI':'Professional nursing graduates, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_227', 'DescripcionI':'Psychiatric care beds, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_228', 'DescripcionI':'Psychiatric care beds, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_229', 'DescripcionI':'Psychiatrists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_230', 'DescripcionI':'Psychiatrists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_231', 'DescripcionI':'Publicly owned hospitals, per 100 000 population', 'Unidad':'FACIL_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_232', 'DescripcionI':'Publicly owned hospitals, total number', 'Unidad':'NUM_FACIL', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_233', 'DescripcionI':'Radiation therapy equipment in ambulatory setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_234', 'DescripcionI':'Radiation therapy equipment in ambulatory setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_235', 'DescripcionI':'Radiation therapy equipment in hospital setting, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_236', 'DescripcionI':'Radiation therapy equipment in hospital setting, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_237', 'DescripcionI':'Radiation therapy equipment, % of equipment in ambulatory setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_238', 'DescripcionI':'Radiation therapy equipment, % of equipment in hospital setting', 'Unidad':'PERCENT', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_239', 'DescripcionI':'Radiation therapy equipment, per 100 000 population', 'Unidad':'EQUIP_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_240', 'DescripcionI':'Radiation therapy equipment, total number', 'Unidad':'NUM_EQUIP', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_241', 'DescripcionI':'Specialist medical practitioners, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_242', 'DescripcionI':'Specialist medical practitioners, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_243', 'DescripcionI':'Surgical group of specialists, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_244', 'DescripcionI':'Surgical group of specialists, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_245', 'DescripcionI':'Total hospital beds, per 100 000 population', 'Unidad':'BEDS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_246', 'DescripcionI':'Total hospital beds, total number', 'Unidad':'NUM_BEDS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_247', 'DescripcionI':'Total hospital employment in FTE, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_248', 'DescripcionI':'Total hospital employment in FTE, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_249', 'DescripcionI':'Total hospital employment, per 100 000 population', 'Unidad':'PROFESS_100K', 'Tipo':'RATIO', 'Categ':'J01'},
	{'CodigoI':'HLTHRES_250', 'DescripcionI':'Total hospital employment, total number', 'Unidad':'NUM_PROFESS', 'Tipo':'COUNT', 'Categ':'J02'}
];
db.Indicador.insertMany(Indicador)

